FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore src/KnowledgeHub.DbMigrator/KnowledgeHub.DbMigrator.csproj && \
    dotnet publish src/KnowledgeHub.DbMigrator/KnowledgeHub.DbMigrator.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:10.0
USER $APP_UID
COPY --from=build /app/publish .
WORKDIR /app
ENTRYPOINT ["dotnet", "KnowledgeHub.DbMigrator.dll"]