import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  }),
];

function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.empty,  // 首页不使用管理端布局
      },
      {
        path: '/knowledge-hub',
        name: '::Menu:KnowledgeHub',
        iconClass: 'fas fa-database',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Resources'
      },
      {
        path: '/resources',
        name: '::Menu:Resources',
        iconClass: 'fas fa-folder-open',
        parentName: '::Menu:KnowledgeHub',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Resources',
      },
      {
        path: '/document-search',
        name: '::Menu:DocumentSearch',
        iconClass: 'fas fa-search',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Search',
      },
      {
        path: '/search',
        name: '::Menu:Search',
        iconClass: 'fas fa-search',
        parentName: '::Menu:DocumentSearch',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Search',
      },
      {
        path: '/admin/indexing-jobs',
        name: '::Menu:IndexingJobs',
        iconClass: 'fas fa-tasks',
        parentName: '::Menu:KnowledgeHub',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Resources',
      },
      {
        path: '/admin/meilisearch',
        name: '::Menu:MeiliSearchDashboard',
        iconClass: 'fas fa-tachometer-alt',
        parentName: '::Menu:KnowledgeHub',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Search.ViewStatistics',
      },
      {
        path: '/news-repository',
        name: '::Menu:NewsRepository',
        iconClass: 'fas fa-newspaper',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.News',
      },
      {
        path: '/admin/search-statistics',
        name: '::Menu:SearchStatistics',
        iconClass: 'fas fa-chart-bar',
        parentName: '::Menu:KnowledgeHub',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Search.ViewStatistics',
      },
      {
        path: '/my/search-history',
        name: '::Menu:SearchHistory',
        iconClass: 'fas fa-history',
        parentName: '::Menu:DocumentSearch',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Search',
      },
      {
        path: '/news',
        name: '::Menu:News',
        iconClass: 'fas fa-newspaper',
        parentName: '::Menu:NewsRepository',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.News',
      },
      {
        path: '/admin/news',
        name: '::Menu:NewsManagement',
        iconClass: 'fas fa-bullhorn',
        parentName: '::Menu:NewsRepository',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.News',
      },
      {
        path: '/micro-majors',
        name: '::Menu:MicroMajorsGroup',
        iconClass: 'fas fa-layer-group',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.MicroMajors',
      },
      {
        path: '/admin/micro-majors',
        name: '::Menu:MicroMajorManagement',
        iconClass: 'fas fa-cubes',
        parentName: '::Menu:MicroMajorsGroup',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.MicroMajors',
      },
      {
        path: '/assessment/double-high/projects',
        name: '::Menu:Assessment',
        iconClass: 'fas fa-chart-pie',
        order: 6,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.DoubleHigh',
      },
      {
        path: '/assessment/double-high/projects',
        name: '::Menu:DoubleHighProjects',
        iconClass: 'fas fa-layer-group',
        parentName: '::Menu:Assessment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.DoubleHigh',
      },
      {
        path: '/assessment/double-high/report-center',
        name: '::Menu:DoubleHighReportCenter',
        iconClass: 'fas fa-file-export',
        parentName: '::Menu:Assessment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.DoubleHigh',
      },
      {
        path: '/admin/assessment/double-high',
        name: '::Menu:DoubleHighManagement',
        iconClass: 'fas fa-sliders-h',
        parentName: '::Menu:Assessment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.DoubleHigh.ManageProject',
      },
      {
        path: '/employment/jobs',
        name: '::Menu:Employment',
        iconClass: 'fas fa-briefcase',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment',
      },
      {
        path: '/employment/jobs',
        name: '::Menu:EmploymentJobs',
        iconClass: 'fas fa-search-dollar',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment',
      },
      {
        path: '/employment/employer-profile',
        name: '::Menu:EmployerProfile',
        iconClass: 'fas fa-building',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.PublishJob',
      },
      {
        path: '/employment/my-resumes',
        name: '::Menu:MyResumes',
        iconClass: 'fas fa-file-lines',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.ManageResume',
      },
      {
        path: '/employment/my-applications',
        name: '::Menu:MyApplications',
        iconClass: 'fas fa-paper-plane',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.ViewMyApplication',
      },
      {
        path: '/employment/my-guidance',
        name: '::Menu:MyGuidance',
        iconClass: 'fas fa-compass',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment',
      },
      {
        path: '/admin/employment/applications',
        name: '::Menu:EmploymentApplicationManagement',
        iconClass: 'fas fa-clipboard-check',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.ManageApplication',
      },
      {
        path: '/admin/employment/jobs',
        name: '::Menu:EmploymentJobManagement',
        iconClass: 'fas fa-clipboard-list',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.PublishJob',
      },
      {
        path: '/admin/employment/interviews',
        name: '::Menu:EmploymentInterviewManagement',
        iconClass: 'fas fa-calendar-check',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.ScheduleInterview',
      },
      {
        path: '/admin/employment/statistics',
        name: '::Menu:EmploymentStatistics',
        iconClass: 'fas fa-chart-column',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Employment.ViewStatistics',
      },
      {
        path: '/admin/recruitment-live',
        name: '::Menu:RecruitmentLive',
        iconClass: 'fas fa-video',
        parentName: '::Menu:Employment',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.RecruitmentLive.Create',
      },
      {
        path: '/practicum/projects',
        name: '::Menu:PracticumGroup',
        iconClass: 'fas fa-briefcase',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Practicum',
      },
      {
        path: '/admin/practicum/projects',
        name: '::Menu:PracticumManagement',
        iconClass: 'fas fa-chalkboard-teacher',
        parentName: '::Menu:PracticumGroup',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Practicum',
      },
      {
        path: '/ai',
        name: '::Menu:AI',
        iconClass: 'fas fa-robot',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI',
      },
      {
        path: '/ai/chat',
        name: '::Menu:AIChat',
        parentName: '::Menu:AI',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI.Chat',
      },
      {
        path: '/ai/lesson-plan',
        name: '::Menu:LessonPlan',
        parentName: '::Menu:AI',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI.LessonPlan',
      },
      {
        path: '/ai/case-analysis',
        name: '::Menu:CaseAnalysis',
        parentName: '::Menu:AI',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI.CaseAnalysis',
      },
      {
        path: '/ai/career-guidance',
        name: '::Menu:CareerGuidance',
        parentName: '::Menu:AI',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI.CareerGuidance',
      },
      {
        path: '/ai/model-management',
        name: '::Menu:ModelManagement',
        parentName: '::Menu:AI',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.AI',
      },
      {
        path: '/admin/exercise',
        name: '::Menu:ExerciseManagement',
        parentName: 'AbpUiNavigation::Menu:Administration',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Exercises',
      },
      {
        path: '/learning',
        name: '::Menu:Learning',
        iconClass: 'fas fa-graduation-cap',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses',
      },
      {
        path: '/learning/course-list',
        name: '::Menu:CourseList',
        iconClass: 'fas fa-book-open',
        parentName: '::Menu:Learning',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses',
      },
      {
        path: '/learning/student-enrollment',
        name: '::Menu:StudentEnrollment',
        iconClass: 'fas fa-user-plus',
        parentName: '::Menu:Learning',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses.ManageEnrollment',
      },
      {
        path: '/learning/chapter-management',
        name: '::Menu:ChapterManagement',
        iconClass: 'fas fa-sitemap',
        parentName: '::Menu:Learning',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses.Edit',
      },
      {
        path: '/learning/exercise-management',
        name: '::Menu:ExerciseManagement',
        iconClass: 'fas fa-pen-to-square',
        parentName: '::Menu:Learning',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses.Edit',
      },
      {
        path: '/learning/chapter-exercise',
        name: '::Menu:ChapterExercise',
        iconClass: 'fas fa-link',
        parentName: '::Menu:Learning',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses.Edit',
      },
      {
        path: '/learning/knowledge-graph/:courseId',
        name: '::Menu:KnowledgeGraph',
        parentName: '::Menu:Learning',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses',
        invisible: true,
      },
      {
        path: '/learning/learning-progress',
        name: '::Menu:LearningProgress',
        iconClass: 'fas fa-chart-line',
        parentName: '::Menu:Learning',
        order: 6,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Courses',
      },
      {
        path: '/learning/learning-statistics',
        name: '::Menu:LearningStatistics',
        iconClass: 'fas fa-chart-bar',
        parentName: '::Menu:Learning',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.Learning.ViewStatistics',
      },
      {
        path: '/teaching',
        name: '::Menu:TeachingWorkbench',
        iconClass: 'fas fa-robot',
        order: 6,
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.TeachingAgents',
      },
      {
        path: '/teaching/agents',
        name: '::Menu:TeachingAgents',
        iconClass: 'fas fa-microchip',
        parentName: '::Menu:TeachingWorkbench',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.TeachingAgents.Manage',
      },
      {
        path: '/teaching/agent-tasks',
        name: '::Menu:TeachingAgentTasks',
        iconClass: 'fas fa-share-nodes',
        parentName: '::Menu:TeachingWorkbench',
        layout: eLayoutType.application,
        requiredPolicy: 'KnowledgeHub.TeachingAgents.Assign',
      },
      {
        path: '/student',
        name: '::Menu:StudentPortal',
        layout: eLayoutType.empty,
        invisible: true,
      },
  ]);
}
