// <auto-generated />
using System;
using KnowledgeHub.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace KnowledgeHub.Migrations
{
    [DbContext(typeof(KnowledgeHubDbContext))]
    [Migration("20260622000000_AddInterviewerIdToInterviewSchedule")]
    partial class AddInterviewerIdToInterviewSchedule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DocumentMappingsEnabled", true)
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasPostgresExtension("uuid-ossp");

            // 仅做占位声明以通过 migrations tooling 校验；真实模型以 KnowledgeHubDbContextModelSnapshot.cs 为准。
            modelBuilder.HasDefaultSchema("public");
            modelBuilder.Entity("KnowledgeHub.Employment.InterviewSchedule", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Guid?>("InterviewerId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.ToTable("AppInterviewSchedules", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
